# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilephoto',
            name='profile_photo',
            field=models.ImageField(max_length=2000, upload_to=b''),
        ),
    ]
