from django.conf.urls import patterns, url
from django.views.generic import TemplateView

urlpatterns = patterns('',
   url(r'^(?P<username>\w+)/$', 'users.views.profile', name='profile'),
   url(r'^404$', TemplateView.as_view(template_name='users/profile_not_exist.html')),
   url(r'^403$', TemplateView.as_view(template_name = '403.html')),
   url(r'^req-fb$', TemplateView.as_view(template_name = 'req.html')),
   url(r'^help$', TemplateView.as_view(template_name = 'help.html')),
   url(r'^edit/cover-photo/$', 'users.views.edit_cover_photo', name='edit_cover_photo'),
   url(r'^edit/profile-photo/(?P<image_id>\d+)$', 'users.views.edit_profile_photo', name='edit_profile_photo'),
   url(r'^edit/profile-photo/$', 'users.views.edit_profile_photo', name='edit_profile_photo'),
   url(r'^edit/profile/$', 'users.views.edit_profile', name='edit_profile'),
   url(r'^settings$', 'users.views.settings', name='settings'),
   url(r'^(?P<username>\w+)/friends$', 'users.views.friends', name='friends'),
   url(r'^(?P<username>\w+)/stories$', 'users.views.stories', name='stories'),
   url(r'^upload-new-story$', 'users.views.upload_new_story', name='upload_new_story'),
   url(r'^uploading-finished/(?P<photo_id>\d+)$', 'users.views.uploading_finished', name = 'uploading_finished'),
   url(r'^write-story$', 'users.views.write_story', name = 'write_story'),
   url(r'^check-for-taken-date/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})$','users.views.check_for_taken_date', name='check_for_taken_date'),
   url(r'^write-new-status$', 'users.views.write_status', name='write_status'),
   url(r'^send-friend-request/(?P<recipient_id>\d+)$','users.views.send_friend_request',name='send_friend_request'),
   url(r'^cancel-friend-request/(?P<recipient_id>\d+)$','users.views.cancel_friend_request',name='cancel_friend_request'),
   url(r'^reject-friend-request/(?P<sender_id>\d+)$', 'users.views.reject_friend_request', name='reject_friend_request'),
   url(r'^delete-from-friends/(?P<friend_id>\d+)$', 'users.views.delete_from_friends', name='delete_from_friends'),
   url(r'^accept-friend-request/(?P<sender_id>\d+)$','users.views.accept_friend_request',name='accept_friend_request'),
   url(r'^(?P<username>\w+)/daily-photo/$', 'users.views.browse_daily_photo_all', name='browse_daily_photo_all'),
   url(r'^(?P<username>\w+)/daily-photo/(?P<photo_id>\d+)$', 'users.views.browse_daily_photo_single', name='browse_daily_photo_single'),
   url(r'^(?P<username>\w+)/daily-photo/lightbox/(?P<photo_id>\d+)$', 'users.views.browse_daily_photo_single_lightbox', name='browse_daily_photo_single_lightbox'),

   url(r'^(?P<username>\w+)/profile-photo/$', 'users.views.browse_profile_photos_all', name='browse_profile_photo_all'),
   #url(r'^(?P<username>\w+)/profile-photo/(?P<photo_id>\d+)$', 'users.views.browse_profile_photos_single', name='browse_profile_photo_single'),

   url(r'^(?P<username>\w+)/cover-photo/$', 'users.views.browse_cover_photos_all', name='browse_cover_photo_all'),
   #url(r'^(?P<username>\w+)/cover-photo/(?P<photo_id>\d+)$', 'users.views.browse_cover_photos_single', name='browse_cover_photo_single'),


   url(r'^(?P<username>\w+)/profile$', 'users.views.user_profile_info', name='user_profile_info'),
   url(r'^set-rating/$', 'users.views.set_rating'),
   url(r'^do-comment/(?P<dailyphoto_id>\d+)$', 'users.views.do_comment', name='do_comment'),
   url(r'^edit-comment/(?P<comment_id>\d+)$', 'users.views.edit_comment', name='edit_comment'),
   url(r'^edit-story/(?P<dp_id>\d+)$', 'users.views.edit_story', name='edit_story'),
   url(r'^delete-comment/(?P<comment_id>\d+)$', 'users.views.delete_comment', name='delete_comment'),
   url(r'^set-rating/$', 'users.views.set_rating'),
   url(r'^edit-privacy$', 'users.views.edit_privacy_settings', name='edit_privacy_settings'),
   url(r'^show-likes-history/(?P<photo_id>\d+)$','users.views.show_likes_history', name='show_likes_history'),
   url(r'^find-friends$','users.views.find_friends', name='find_friends'),
   url(r'^do-find-friends$','users.views.do_find_friends', name='do_find_friends'),
   url(r'^facebook-settings$','users.views.facebook_settings', name='facebook_settings'),
   url(r'^change-facebook-settings$','users.views.change_facebook_settings', name='change_facebook_settings'),
   url(r'^(?P<username>\w+)/testimonials$', 'users.views.testimonials', name='testimonials'),
   url(r'^(?P<username>\w+)/testimonials/(?P<key>\d+)$', 'users.views.testimonials', name='testimonials'),
   url(r'^(?P<username>\w+)/write-testimonial$', 'users.views.write_testimonial', name='write_testimonial'),
   url(r'^delete-daily-photo/(?P<dp_id>\d+)$', 'users.views.delete_daily_photo', name='delete_daily_photo'),
)
