from django.conf.urls import url
from django.views.generic import TemplateView

from .views import *

urlpatterns = [
    url(r'^(?P<username>\w+)/$', profile, name='profile'),
    url(r'^404$', TemplateView.as_view(template_name='users/profile_not_exist.html')),
    url(r'^403$', TemplateView.as_view(template_name='403.html')),
    url(r'^req-fb$', TemplateView.as_view(template_name='req.html')),
    url(r'^help$', TemplateView.as_view(template_name='help.html')),
    url(r'^edit/cover-photo/$', edit_cover_photo, name='edit_cover_photo'),
    url(r'^edit/profile-photo/(?P<image_id>\d+)$', edit_profile_photo,
        name='edit_profile_photo'),
    url(r'^edit/profile-photo/$', edit_profile_photo, name='edit_profile_photo'),
    url(r'^edit/profile/$', edit_profile, name='edit_profile'),
    url(r'^settings$', settings, name='settings'),
    url(r'^(?P<username>\w+)/friends$', friends, name='friends'),
    url(r'^(?P<username>\w+)/stories$', stories, name='stories'),
    url(r'^upload-new-story$', upload_new_story, name='upload_new_story'),
    url(r'^uploading-finished/(?P<photo_id>\d+)$', uploading_finished,
        name='uploading_finished'),
    url(r'^write-story$', write_story, name='write_story'),
    url(r'^check-for-taken-date/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})$',
        check_for_taken_date, name='check_for_taken_date'),
    url(r'^write-new-status$', write_status, name='write_status'),
    url(r'^send-friend-request/(?P<recipient_id>\d+)$', send_friend_request,
        name='send_friend_request'),
    url(r'^cancel-friend-request/(?P<recipient_id>\d+)$', cancel_friend_request,
        name='cancel_friend_request'),
    url(r'^reject-friend-request/(?P<sender_id>\d+)$', reject_friend_request,
        name='reject_friend_request'),
    url(r'^delete-from-friends/(?P<friend_id>\d+)$', delete_from_friends,
        name='delete_from_friends'),
    url(r'^accept-friend-request/(?P<sender_id>\d+)$', accept_friend_request,
        name='accept_friend_request'),
    url(r'^(?P<username>\w+)/daily-photo/$', browse_daily_photo_all,
        name='browse_daily_photo_all'),
    url(r'^(?P<username>\w+)/daily-photo/(?P<photo_id>\d+)$',
        browse_daily_photo_single, name='browse_daily_photo_single'),
    url(r'^(?P<username>\w+)/daily-photo/lightbox/(?P<photo_id>\d+)$',
        browse_daily_photo_single_lightbox, name='browse_daily_photo_single_lightbox'),

    url(r'^(?P<username>\w+)/profile-photo/$', browse_profile_photos_all,
        name='browse_profile_photo_all'),
    # url(r'^(?P<username>\w+)/profile-photo/(?P<photo_id>\d+)$', 'users.views.browse_profile_photos_single', name='browse_profile_photo_single'),

    url(r'^(?P<username>\w+)/cover-photo/$', browse_cover_photos_all,
        name='browse_cover_photo_all'),
    # url(r'^(?P<username>\w+)/cover-photo/(?P<photo_id>\d+)$', 'users.views.browse_cover_photos_single', name='browse_cover_photo_single'),


    url(r'^(?P<username>\w+)/profile$', user_profile_info, name='user_profile_info'),
    url(r'^set-rating/$', set_rating),
    url(r'^do-comment/(?P<dailyphoto_id>\d+)$', do_comment, name='do_comment'),
    url(r'^edit-comment/(?P<comment_id>\d+)$', edit_comment, name='edit_comment'),
    url(r'^edit-story/(?P<dp_id>\d+)$', edit_story, name='edit_story'),
    url(r'^delete-comment/(?P<comment_id>\d+)$', delete_comment,
        name='delete_comment'),
    url(r'^set-rating/$', set_rating),
    url(r'^edit-privacy$', edit_privacy_settings, name='edit_privacy_settings'),
    url(r'^show-likes-history/(?P<photo_id>\d+)$', show_likes_history,
        name='show_likes_history'),
    url(r'^find-friends$', find_friends, name='find_friends'),
    url(r'^do-find-friends$', do_find_friends, name='do_find_friends'),
    url(r'^facebook-settings$', facebook_settings, name='facebook_settings'),
    url(r'^change-facebook-settings$', change_facebook_settings,
        name='change_facebook_settings'),
    url(r'^(?P<username>\w+)/testimonials$', testimonials, name='testimonials'),
    url(r'^(?P<username>\w+)/testimonials/(?P<key>\d+)$', testimonials,
        name='testimonials'),
    url(r'^(?P<username>\w+)/write-testimonial$', write_testimonial,
        name='write_testimonial'),
    url(r'^delete-daily-photo/(?P<dp_id>\d+)$', delete_daily_photo,
        name='delete_daily_photo'),
]
